package com.wgt.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * Feature注解处理器
 * 扫描@FeatureProvider注解并生成扩展属性和注册代码
 */
class FeatureProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val options: Map<String, String>
) : SymbolProcessor {

    private val features = mutableListOf<FeatureInfo>()

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(
            "com.wgt.architecture.di.annotations.FeatureProvider"
        )

        val unableToProcess = mutableListOf<KSAnnotated>()

        symbols.filterIsInstance<KSClassDeclaration>().forEach { classDecl ->
            try {
                processFeatureClass(classDecl)
            } catch (e: Exception) {
                logger.error("处理 ${classDecl.qualifiedName?.asString()} 时出错: ${e.message}", classDecl)
                unableToProcess.add(classDecl)
            }
        }

        return unableToProcess
    }

    override fun finish() {
        if (features.isEmpty()) {
            logger.info("没有发现任何 @FeatureProvider 注解")
            return
        }

        logger.info("发现 ${features.size} 个 Feature，开始生成代码...")

        generateExtensionProperties()
        generateRegistrationFunction()

        logger.info("代码生成完成")
    }

    private fun processFeatureClass(classDecl: KSClassDeclaration) {
        // 验证类是否继承自 Feature 或 IFeature
        val isValidFeature = classDecl.superTypes.any { superType ->
            val resolvedType = superType.resolve()
            val qualifiedName = resolvedType.declaration.qualifiedName?.asString()
            qualifiedName == "com.wgt.architecture.feature.Feature" ||
                    qualifiedName == "com.wgt.architecture.feature.IFeature"
        }

        if (!isValidFeature) {
            logger.error(
                "@FeatureProvider 只能用于继承自 Feature 或 IFeature 的类",
                classDecl
            )
            return
        }

        // 获取注解参数
        val annotation = classDecl.annotations.first {
            it.shortName.asString() == "FeatureProvider"
        }

        val propertyName = annotation.arguments
            .find {
                it.name?.asString()?.contains("propertyName") == true && it.value?.toString()?.isNotEmpty() == true
            }
            ?.value as? String
            ?: generatePropertyName(classDecl.simpleName.asString())

        val lifecycleArg = annotation.arguments
            .find { it.name?.asString() == "lifecycle" }
            ?.value

        val lifecycle = when (lifecycleArg) {
            is KSClassDeclaration -> lifecycleArg.simpleName.asString()
            is String -> lifecycleArg
            else -> "SINGLETON"
        }

        val featureInfo = FeatureInfo(
            className = classDecl.qualifiedName?.asString() ?: return,
            simpleName = classDecl.simpleName.asString(),
            propertyName = propertyName,
            lifecycle = lifecycle,
            packageName = classDecl.packageName.asString()
        )

        features.add(featureInfo)

        logger.info("处理 Feature: ${featureInfo.simpleName} -> ${featureInfo.propertyName}")
    }

    private fun generatePropertyName(className: String): String {
        return className
            .removeSuffix("Feature")
            .replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
            .replaceFirstChar { it.lowercase() }
    }

    private fun generateExtensionProperties() {
        // 按包名分组聚合所有Feature
        val featuresByPackage = features.groupBy { it.packageName }
        
        // 为每个包生成一个FeatureExtensions.kt文件
        featuresByPackage.forEach { (packageName, packageFeatures) ->
            val fileSpec = FileSpec.builder(
                packageName = packageName,
                fileName = "FeatureExtensions"
            ).apply {
                addFileComment("Auto-generated by KSP. Do not modify.")
                addFileComment("Generated at: ${System.currentTimeMillis()}")
                
                // 为该包下的所有Feature生成扩展属性和初始化函数
                packageFeatures.forEach { feature ->
                    // 生成扩展属性
                    addProperty(
                        PropertySpec.builder(
                            name = feature.propertyName,
                            type = ClassName.bestGuess(feature.className)
                        )
                            .receiver(ClassName("com.wgt.architecture.manager.claim", "IFeatureManager"))
                            .delegate("inject()")
                            .addKdoc(
                                """
                                Auto-generated extension property for ${feature.simpleName}
                                
                                Usage:
                                ```kotlin
                                val feature = manager.feature.${feature.propertyName}
                                ```
                                """.trimIndent()
                            )
                            .build()
                    )
                    
                    // 生成初始化函数
                    val initFunctionName = "init${feature.simpleName}"
                    val initFunctionSpec = FunSpec.builder(initFunctionName)
                        .addKdoc(
                            """
                            Auto-generated initialization function for ${feature.simpleName}.
                            
                            This function is called by InitFeature() during application initialization.
                            """.trimIndent()
                        )
                        .addStatement(
                            "registerFeature<%T>(Lifecycle.%L) { %T() }",
                            ClassName.bestGuess(feature.className),
                            feature.lifecycle,
                            ClassName.bestGuess(feature.className)
                        )
                        .build()
                    
                    addFunction(initFunctionSpec)
                }
                
                addImport("com.wgt.architecture.di", "inject")
                addImport("com.wgt.architecture.di", "Lifecycle")
                addImport("com.wgt.architecture.feature", "registerFeature")
            }.build()
            
            fileSpec.writeTo(codeGenerator, Dependencies(false))
        }
    }

    private fun generateRegistrationFunction() {
        // 不再生成 InitFeature.kt 文件
        // 该文件由 Gradle 任务负责更新
        logger.info("InitFeature.kt 文件将由 Gradle 任务 updateInitFeature 负责更新")
    }
}

/**
 * Feature元数据
 */
data class FeatureInfo(
    val className: String,
    val simpleName: String,
    val propertyName: String,
    val lifecycle: String,
    val packageName: String
)
