package com.wgt.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * Manager 注解处理器
 * 扫描 @ManagerProvider 注解并自动生成注册函数
 * 
 * 使用方式：
 * 1. 在 commonMain 的 expect class 上添加 @ManagerProvider 注解
 * 2. 在 expect/actual 类中提供 companion object { fun getInstance() }
 * 3. KSP 自动生成 initXxxManager() 注册函数
 */
class ManagerProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val options: Map<String, String>
) : SymbolProcessor {

    private val managers = mutableListOf<ManagerInfo>()

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(
            "com.wgt.architecture.di.annotations.ManagerProvider"
        )

        val unableToProcess = mutableListOf<KSAnnotated>()

        symbols.filterIsInstance<KSClassDeclaration>().forEach { classDecl ->
            try {
                processManagerClass(classDecl)
            } catch (e: Exception) {
                logger.error("处理 ${classDecl.qualifiedName?.asString()} 时出错: ${e.message}", classDecl)
                unableToProcess.add(classDecl)
            }
        }

        return unableToProcess
    }

    override fun finish() {
        if (managers.isEmpty()) {
            logger.info("没有发现任何 @ManagerProvider 注解")
            return
        }

        logger.info("发现 ${managers.size} 个 Manager，开始生成代码...")

        managers.forEach { manager ->
            try {
                generateRegistrationFunction(manager)
                logger.info("生成完成: ${manager.simpleName}")
            } catch (e: Exception) {
                logger.error("生成 ${manager.simpleName} 代码时出错: ${e.message}")
            }
        }
    }

    private fun processManagerClass(classDecl: KSClassDeclaration) {
        // 只处理 expect 类（在 commonMain 中声明）
        val isExpect = classDecl.modifiers.any { it.name == "EXPECT" }
        if (!isExpect) {
            logger.info("跳过非 expect 类: ${classDecl.simpleName.asString()}")
            return
        }

        // 验证类是否实现 IManager 接口
        val isValidManager = classDecl.superTypes.any { superType ->
            val resolvedType = superType.resolve()
            val qualifiedName = resolvedType.declaration.qualifiedName?.asString()
            qualifiedName == "com.wgt.architecture.manager.IManager"
        }

        if (!isValidManager) {
            logger.warn(
                "${classDecl.simpleName.asString()} 可能未直接实现 IManager，请确保它继承自 IManager 或其子接口",
                classDecl
            )
        }

        // 获取注解参数
        val annotation = classDecl.annotations.first {
            it.shortName.asString() == "ManagerProvider"
        }

        val interfaceClass = annotation.arguments
            .find { it.name?.asString() == "interfaceClass" }
            ?.value as? String
            ?: inferInterfaceClass(classDecl)

        val initFunctionName = annotation.arguments
            .find { it.name?.asString() == "initFunctionName" }
            ?.value as? String
            ?: "init${classDecl.simpleName.asString()}"

        val lifecycleArg = annotation.arguments
            .find { it.name?.asString() == "lifecycle" }
            ?.value

        val lifecycle = when (lifecycleArg) {
            is KSClassDeclaration -> lifecycleArg.simpleName.asString()
            is String -> lifecycleArg
            else -> "SINGLETON"
        }

        val managerInfo = ManagerInfo(
            className = classDecl.qualifiedName?.asString() ?: return,
            simpleName = classDecl.simpleName.asString(),
            interfaceClass = interfaceClass,
            initFunctionName = initFunctionName,
            lifecycle = lifecycle,
            packageName = classDecl.packageName.asString()
        )

        managers.add(managerInfo)

        logger.info("处理 Manager: ${managerInfo.simpleName} -> ${managerInfo.interfaceClass}")
    }

    private fun inferInterfaceClass(classDecl: KSClassDeclaration): String {
        // 从 superTypes 中找到包含 IManager 的接口
        val superInterface = classDecl.superTypes
            .map { it.resolve().declaration.qualifiedName?.asString() ?: "" }
            .firstOrNull { it.startsWith("I") && it != "com.wgt.architecture.manager.IManager" }
        
        return superInterface ?: run {
            // 默认推断：类名去掉 Manager，加 I 前缀
            val simpleName = classDecl.simpleName.asString()
            "I${simpleName}"
        }
    }

    /**
     * 生成注册函数
     */
    private fun generateRegistrationFunction(manager: ManagerInfo) {
        val fileSpec = FileSpec.builder(
            packageName = manager.packageName,
            fileName = "${manager.initFunctionName}.generated"
        ).apply {
            addFileComment("Auto-generated by KSP. Do not modify.")
            addFileComment("Generated at: ${System.currentTimeMillis()}")
            
            val interfaceType = ClassName.bestGuess(manager.interfaceClass)
            val managerClass = ClassName.bestGuess(manager.className)
            
            val funSpec = FunSpec.builder(manager.initFunctionName)
                .addKdoc(
                    """
                    Auto-generated initialization function for ${manager.simpleName}.
                    
                    Register ${manager.simpleName} to the global Manager system.
                    
                    Usage:
                    ```kotlin
                    fun InitManager() {
                        ${manager.initFunctionName}()
                    }
                    ```
                    """.trimIndent()
                )
                .addStatement(
                    "registerManager<%T>(Lifecycle.%L) { %T.getInstance() }",
                    interfaceType,
                    manager.lifecycle,
                    managerClass
                )
                .build()
            
            addFunction(funSpec)
            addImport("com.wgt.architecture.di", "Lifecycle")
            addImport("com.wgt.architecture.manager", "registerManager")
            
        }.build()

        fileSpec.writeTo(codeGenerator, Dependencies(false))
    }
}

/**
 * Manager 元数据
 */
data class ManagerInfo(
    val className: String,
    val simpleName: String,
    val interfaceClass: String,
    val initFunctionName: String,
    val lifecycle: String,
    val packageName: String
)
