// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: media.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Media types
type MediaType int32

const (
	MediaType_IMAGE      MediaType = 0
	MediaType_LIVE_PHOTO MediaType = 1
	MediaType_VIDEO      MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "IMAGE",
		1: "LIVE_PHOTO",
		2: "VIDEO",
	}
	MediaType_value = map[string]int32{
		"IMAGE":      0,
		"LIVE_PHOTO": 1,
		"VIDEO":      2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

// Thumbnail size preset
type ThumbnailSize int32

const (
	ThumbnailSize_THUMBNAIL_SMALL  ThumbnailSize = 0 // ~128px on the long edge
	ThumbnailSize_THUMBNAIL_MEDIUM ThumbnailSize = 1 // ~256px
	ThumbnailSize_THUMBNAIL_LARGE  ThumbnailSize = 2 // ~512px
)

// Enum value maps for ThumbnailSize.
var (
	ThumbnailSize_name = map[int32]string{
		0: "THUMBNAIL_SMALL",
		1: "THUMBNAIL_MEDIUM",
		2: "THUMBNAIL_LARGE",
	}
	ThumbnailSize_value = map[string]int32{
		"THUMBNAIL_SMALL":  0,
		"THUMBNAIL_MEDIUM": 1,
		"THUMBNAIL_LARGE":  2,
	}
)

func (x ThumbnailSize) Enum() *ThumbnailSize {
	p := new(ThumbnailSize)
	*p = x
	return p
}

func (x ThumbnailSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThumbnailSize) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[1].Descriptor()
}

func (ThumbnailSize) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[1]
}

func (x ThumbnailSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThumbnailSize.Descriptor instead.
func (ThumbnailSize) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

// Media metadata
type MediaMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename         string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Type             MediaType              `protobuf:"varint,3,opt,name=type,proto3,enum=media.MediaType" json:"type,omitempty"`
	Size             int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	MimeType         string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExifData         map[string]string      `protobuf:"bytes,8,rep,name=exif_data,json=exifData,proto3" json:"exif_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsLivePhoto      bool                   `protobuf:"varint,9,opt,name=is_live_photo,json=isLivePhoto,proto3" json:"is_live_photo,omitempty"`
	LivePhotoVideoId string                 `protobuf:"bytes,10,opt,name=live_photo_video_id,json=livePhotoVideoId,proto3" json:"live_photo_video_id,omitempty"` // For Live Photos, reference to video file
	Width            int32                  `protobuf:"varint,11,opt,name=width,proto3" json:"width,omitempty"`                                                  // Image width in pixels
	Height           int32                  `protobuf:"varint,12,opt,name=height,proto3" json:"height,omitempty"`                                                // Image height in pixels
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MediaMetadata) Reset() {
	*x = MediaMetadata{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaMetadata) ProtoMessage() {}

func (x *MediaMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaMetadata.ProtoReflect.Descriptor instead.
func (*MediaMetadata) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

func (x *MediaMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MediaMetadata) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_IMAGE
}

func (x *MediaMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MediaMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaMetadata) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MediaMetadata) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *MediaMetadata) GetExifData() map[string]string {
	if x != nil {
		return x.ExifData
	}
	return nil
}

func (x *MediaMetadata) GetIsLivePhoto() bool {
	if x != nil {
		return x.IsLivePhoto
	}
	return false
}

func (x *MediaMetadata) GetLivePhotoVideoId() string {
	if x != nil {
		return x.LivePhotoVideoId
	}
	return ""
}

func (x *MediaMetadata) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaMetadata) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Upload request - streamed for large files
type UploadMediaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadMediaRequest_Metadata
	//	*UploadMediaRequest_ChunkData
	Data          isUploadMediaRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaRequest) Reset() {
	*x = UploadMediaRequest{}
	mi := &file_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaRequest) ProtoMessage() {}

func (x *UploadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMediaRequest) GetData() isUploadMediaRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadMediaRequest) GetMetadata() *MediaMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadMediaRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadMediaRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadMediaRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadMediaRequest_Data interface {
	isUploadMediaRequest_Data()
}

type UploadMediaRequest_Metadata struct {
	Metadata *MediaMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadMediaRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadMediaRequest_Metadata) isUploadMediaRequest_Data() {}

func (*UploadMediaRequest_ChunkData) isUploadMediaRequest_Data() {}

// Upload response
type UploadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaResponse) Reset() {
	*x = UploadMediaResponse{}
	mi := &file_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaResponse) ProtoMessage() {}

func (x *UploadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

func (x *UploadMediaResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *UploadMediaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UploadMediaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get media list request
type GetMediaListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	FilterType    MediaType              `protobuf:"varint,3,opt,name=filter_type,json=filterType,proto3,enum=media.MediaType" json:"filter_type,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,4,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaListRequest) Reset() {
	*x = GetMediaListRequest{}
	mi := &file_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaListRequest) ProtoMessage() {}

func (x *GetMediaListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaListRequest.ProtoReflect.Descriptor instead.
func (*GetMediaListRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{3}
}

func (x *GetMediaListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMediaListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMediaListRequest) GetFilterType() MediaType {
	if x != nil {
		return x.FilterType
	}
	return MediaType_IMAGE
}

func (x *GetMediaListRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

// Get media list response
type GetMediaListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaList     []*MediaMetadata       `protobuf:"bytes,1,rep,name=media_list,json=mediaList,proto3" json:"media_list,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaListResponse) Reset() {
	*x = GetMediaListResponse{}
	mi := &file_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaListResponse) ProtoMessage() {}

func (x *GetMediaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaListResponse.ProtoReflect.Descriptor instead.
func (*GetMediaListResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{4}
}

func (x *GetMediaListResponse) GetMediaList() []*MediaMetadata {
	if x != nil {
		return x.MediaList
	}
	return nil
}

func (x *GetMediaListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetMediaListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMediaListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Delete media request
type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaIds      []string               `protobuf:"bytes,1,rep,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMediaRequest) GetMediaIds() []string {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

// Delete media response
type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,3,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMediaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteMediaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteMediaResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

// Get media metadata request
type GetMediaMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaMetadataRequest) Reset() {
	*x = GetMediaMetadataRequest{}
	mi := &file_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaMetadataRequest) ProtoMessage() {}

func (x *GetMediaMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMediaMetadataRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{7}
}

func (x *GetMediaMetadataRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

// Get media metadata response
type GetMediaMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *MediaMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaMetadataResponse) Reset() {
	*x = GetMediaMetadataResponse{}
	mi := &file_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaMetadataResponse) ProtoMessage() {}

func (x *GetMediaMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMediaMetadataResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{8}
}

func (x *GetMediaMetadataResponse) GetMetadata() *MediaMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Get media stream (original binary) request
type GetMediaStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // byte offset to start reading from (0-based), optional, defaults to 0
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"` // number of bytes to stream, 0 means until EOF
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaStreamRequest) Reset() {
	*x = GetMediaStreamRequest{}
	mi := &file_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaStreamRequest) ProtoMessage() {}

func (x *GetMediaStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaStreamRequest.ProtoReflect.Descriptor instead.
func (*GetMediaStreamRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{9}
}

func (x *GetMediaStreamRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *GetMediaStreamRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetMediaStreamRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// Streamed response chunk for GetMediaStream
type GetMediaStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*GetMediaStreamResponse_Metadata
	//	*GetMediaStreamResponse_ChunkData
	Data          isGetMediaStreamResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaStreamResponse) Reset() {
	*x = GetMediaStreamResponse{}
	mi := &file_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaStreamResponse) ProtoMessage() {}

func (x *GetMediaStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaStreamResponse.ProtoReflect.Descriptor instead.
func (*GetMediaStreamResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{10}
}

func (x *GetMediaStreamResponse) GetData() isGetMediaStreamResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetMediaStreamResponse) GetMetadata() *MediaMetadata {
	if x != nil {
		if x, ok := x.Data.(*GetMediaStreamResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *GetMediaStreamResponse) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*GetMediaStreamResponse_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isGetMediaStreamResponse_Data interface {
	isGetMediaStreamResponse_Data()
}

type GetMediaStreamResponse_Metadata struct {
	Metadata *MediaMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // sent once as the first message
}

type GetMediaStreamResponse_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"` // file bytes in order; empty chunk signals EOF
}

func (*GetMediaStreamResponse_Metadata) isGetMediaStreamResponse_Data() {}

func (*GetMediaStreamResponse_ChunkData) isGetMediaStreamResponse_Data() {}

// Get thumbnail request
type GetThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Size          ThumbnailSize          `protobuf:"varint,2,opt,name=size,proto3,enum=media.ThumbnailSize" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThumbnailRequest) Reset() {
	*x = GetThumbnailRequest{}
	mi := &file_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailRequest) ProtoMessage() {}

func (x *GetThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailRequest.ProtoReflect.Descriptor instead.
func (*GetThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{11}
}

func (x *GetThumbnailRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *GetThumbnailRequest) GetSize() ThumbnailSize {
	if x != nil {
		return x.Size
	}
	return ThumbnailSize_THUMBNAIL_SMALL
}

// Get thumbnail response
type GetThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThumbnailResponse) Reset() {
	*x = GetThumbnailResponse{}
	mi := &file_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailResponse) ProtoMessage() {}

func (x *GetThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailResponse.ProtoReflect.Descriptor instead.
func (*GetThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{12}
}

func (x *GetThumbnailResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetThumbnailResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetThumbnailResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetThumbnailResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\x05media\"\xcf\x03\n" +
	"\rMediaMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.media.MediaTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12?\n" +
	"\texif_data\x18\b \x03(\v2\".media.MediaMetadata.ExifDataEntryR\bexifData\x12\"\n" +
	"\ris_live_photo\x18\t \x01(\bR\visLivePhoto\x12-\n" +
	"\x13live_photo_video_id\x18\n" +
	" \x01(\tR\x10livePhotoVideoId\x12\x14\n" +
	"\x05width\x18\v \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\f \x01(\x05R\x06height\x1a;\n" +
	"\rExifDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x12UploadMediaRequest\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.media.MediaMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"b\n" +
	"\x13UploadMediaResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9c\x01\n" +
	"\x13GetMediaListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x121\n" +
	"\vfilter_type\x18\x03 \x01(\x0e2\x10.media.MediaTypeR\n" +
	"filterType\x12!\n" +
	"\fsearch_query\x18\x04 \x01(\tR\vsearchQuery\"\x9d\x01\n" +
	"\x14GetMediaListResponse\x123\n" +
	"\n" +
	"media_list\x18\x01 \x03(\v2\x14.media.MediaMetadataR\tmediaList\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"1\n" +
	"\x12DeleteMediaRequest\x12\x1b\n" +
	"\tmedia_ids\x18\x01 \x03(\tR\bmediaIds\"l\n" +
	"\x13DeleteMediaResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rdeleted_count\x18\x03 \x01(\x05R\fdeletedCount\"4\n" +
	"\x17GetMediaMetadataRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"L\n" +
	"\x18GetMediaMetadataResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.media.MediaMetadataR\bmetadata\"b\n" +
	"\x15GetMediaStreamRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"u\n" +
	"\x16GetMediaStreamResponse\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.media.MediaMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"Z\n" +
	"\x13GetThumbnailRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12(\n" +
	"\x04size\x18\x02 \x01(\x0e2\x14.media.ThumbnailSizeR\x04size\"u\n" +
	"\x14GetThumbnailResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height*1\n" +
	"\tMediaType\x12\t\n" +
	"\x05IMAGE\x10\x00\x12\x0e\n" +
	"\n" +
	"LIVE_PHOTO\x10\x01\x12\t\n" +
	"\x05VIDEO\x10\x02*O\n" +
	"\rThumbnailSize\x12\x13\n" +
	"\x0fTHUMBNAIL_SMALL\x10\x00\x12\x14\n" +
	"\x10THUMBNAIL_MEDIUM\x10\x01\x12\x13\n" +
	"\x0fTHUMBNAIL_LARGE\x10\x022\xd4\x03\n" +
	"\fMediaService\x12F\n" +
	"\vUploadMedia\x12\x19.media.UploadMediaRequest\x1a\x1a.media.UploadMediaResponse(\x01\x12G\n" +
	"\fGetMediaList\x12\x1a.media.GetMediaListRequest\x1a\x1b.media.GetMediaListResponse\x12D\n" +
	"\vDeleteMedia\x12\x19.media.DeleteMediaRequest\x1a\x1a.media.DeleteMediaResponse\x12S\n" +
	"\x10GetMediaMetadata\x12\x1e.media.GetMediaMetadataRequest\x1a\x1f.media.GetMediaMetadataResponse\x12O\n" +
	"\x0eGetMediaStream\x12\x1c.media.GetMediaStreamRequest\x1a\x1d.media.GetMediaStreamResponse0\x01\x12G\n" +
	"\fGetThumbnail\x12\x1a.media.GetThumbnailRequest\x1a\x1b.media.GetThumbnailResponseB\x1bZ\x19media-manager/backend/genb\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_media_proto_goTypes = []any{
	(MediaType)(0),                   // 0: media.MediaType
	(ThumbnailSize)(0),               // 1: media.ThumbnailSize
	(*MediaMetadata)(nil),            // 2: media.MediaMetadata
	(*UploadMediaRequest)(nil),       // 3: media.UploadMediaRequest
	(*UploadMediaResponse)(nil),      // 4: media.UploadMediaResponse
	(*GetMediaListRequest)(nil),      // 5: media.GetMediaListRequest
	(*GetMediaListResponse)(nil),     // 6: media.GetMediaListResponse
	(*DeleteMediaRequest)(nil),       // 7: media.DeleteMediaRequest
	(*DeleteMediaResponse)(nil),      // 8: media.DeleteMediaResponse
	(*GetMediaMetadataRequest)(nil),  // 9: media.GetMediaMetadataRequest
	(*GetMediaMetadataResponse)(nil), // 10: media.GetMediaMetadataResponse
	(*GetMediaStreamRequest)(nil),    // 11: media.GetMediaStreamRequest
	(*GetMediaStreamResponse)(nil),   // 12: media.GetMediaStreamResponse
	(*GetThumbnailRequest)(nil),      // 13: media.GetThumbnailRequest
	(*GetThumbnailResponse)(nil),     // 14: media.GetThumbnailResponse
	nil,                              // 15: media.MediaMetadata.ExifDataEntry
}
var file_media_proto_depIdxs = []int32{
	0,  // 0: media.MediaMetadata.type:type_name -> media.MediaType
	15, // 1: media.MediaMetadata.exif_data:type_name -> media.MediaMetadata.ExifDataEntry
	2,  // 2: media.UploadMediaRequest.metadata:type_name -> media.MediaMetadata
	0,  // 3: media.GetMediaListRequest.filter_type:type_name -> media.MediaType
	2,  // 4: media.GetMediaListResponse.media_list:type_name -> media.MediaMetadata
	2,  // 5: media.GetMediaMetadataResponse.metadata:type_name -> media.MediaMetadata
	2,  // 6: media.GetMediaStreamResponse.metadata:type_name -> media.MediaMetadata
	1,  // 7: media.GetThumbnailRequest.size:type_name -> media.ThumbnailSize
	3,  // 8: media.MediaService.UploadMedia:input_type -> media.UploadMediaRequest
	5,  // 9: media.MediaService.GetMediaList:input_type -> media.GetMediaListRequest
	7,  // 10: media.MediaService.DeleteMedia:input_type -> media.DeleteMediaRequest
	9,  // 11: media.MediaService.GetMediaMetadata:input_type -> media.GetMediaMetadataRequest
	11, // 12: media.MediaService.GetMediaStream:input_type -> media.GetMediaStreamRequest
	13, // 13: media.MediaService.GetThumbnail:input_type -> media.GetThumbnailRequest
	4,  // 14: media.MediaService.UploadMedia:output_type -> media.UploadMediaResponse
	6,  // 15: media.MediaService.GetMediaList:output_type -> media.GetMediaListResponse
	8,  // 16: media.MediaService.DeleteMedia:output_type -> media.DeleteMediaResponse
	10, // 17: media.MediaService.GetMediaMetadata:output_type -> media.GetMediaMetadataResponse
	12, // 18: media.MediaService.GetMediaStream:output_type -> media.GetMediaStreamResponse
	14, // 19: media.MediaService.GetThumbnail:output_type -> media.GetThumbnailResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	file_media_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadMediaRequest_Metadata)(nil),
		(*UploadMediaRequest_ChunkData)(nil),
	}
	file_media_proto_msgTypes[10].OneofWrappers = []any{
		(*GetMediaStreamResponse_Metadata)(nil),
		(*GetMediaStreamResponse_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		EnumInfos:         file_media_proto_enumTypes,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
