// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: media.proto

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MediaService_UploadMedia_FullMethodName      = "/media.MediaService/UploadMedia"
	MediaService_GetMediaList_FullMethodName     = "/media.MediaService/GetMediaList"
	MediaService_DeleteMedia_FullMethodName      = "/media.MediaService/DeleteMedia"
	MediaService_GetMediaMetadata_FullMethodName = "/media.MediaService/GetMediaMetadata"
	MediaService_GetMediaStream_FullMethodName   = "/media.MediaService/GetMediaStream"
	MediaService_GetThumbnail_FullMethodName     = "/media.MediaService/GetThumbnail"
)

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaServiceClient interface {
	UploadMedia(ctx context.Context, opts ...grpc.CallOption) (MediaService_UploadMediaClient, error)
	GetMediaList(ctx context.Context, in *GetMediaListRequest, opts ...grpc.CallOption) (*GetMediaListResponse, error)
	DeleteMedia(ctx context.Context, in *DeleteMediaRequest, opts ...grpc.CallOption) (*DeleteMediaResponse, error)
	GetMediaMetadata(ctx context.Context, in *GetMediaMetadataRequest, opts ...grpc.CallOption) (*GetMediaMetadataResponse, error)
	// Stream the original media binary (chunked). First message carries metadata.
	GetMediaStream(ctx context.Context, in *GetMediaStreamRequest, opts ...grpc.CallOption) (MediaService_GetMediaStreamClient, error)
	// Get a (cached) thumbnail for an image media, generated on demand.
	GetThumbnail(ctx context.Context, in *GetThumbnailRequest, opts ...grpc.CallOption) (*GetThumbnailResponse, error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) UploadMedia(ctx context.Context, opts ...grpc.CallOption) (MediaService_UploadMediaClient, error) {
	stream, err := c.cc.NewStream(ctx, &MediaService_ServiceDesc.Streams[0], MediaService_UploadMedia_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &mediaServiceUploadMediaClient{stream}
	return x, nil
}

type MediaService_UploadMediaClient interface {
	Send(*UploadMediaRequest) error
	CloseAndRecv() (*UploadMediaResponse, error)
	grpc.ClientStream
}

type mediaServiceUploadMediaClient struct {
	grpc.ClientStream
}

func (x *mediaServiceUploadMediaClient) Send(m *UploadMediaRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mediaServiceUploadMediaClient) CloseAndRecv() (*UploadMediaResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadMediaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mediaServiceClient) GetMediaList(ctx context.Context, in *GetMediaListRequest, opts ...grpc.CallOption) (*GetMediaListResponse, error) {
	out := new(GetMediaListResponse)
	err := c.cc.Invoke(ctx, MediaService_GetMediaList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) DeleteMedia(ctx context.Context, in *DeleteMediaRequest, opts ...grpc.CallOption) (*DeleteMediaResponse, error) {
	out := new(DeleteMediaResponse)
	err := c.cc.Invoke(ctx, MediaService_DeleteMedia_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetMediaMetadata(ctx context.Context, in *GetMediaMetadataRequest, opts ...grpc.CallOption) (*GetMediaMetadataResponse, error) {
	out := new(GetMediaMetadataResponse)
	err := c.cc.Invoke(ctx, MediaService_GetMediaMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetMediaStream(ctx context.Context, in *GetMediaStreamRequest, opts ...grpc.CallOption) (MediaService_GetMediaStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &MediaService_ServiceDesc.Streams[1], MediaService_GetMediaStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &mediaServiceGetMediaStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MediaService_GetMediaStreamClient interface {
	Recv() (*GetMediaStreamResponse, error)
	grpc.ClientStream
}

type mediaServiceGetMediaStreamClient struct {
	grpc.ClientStream
}

func (x *mediaServiceGetMediaStreamClient) Recv() (*GetMediaStreamResponse, error) {
	m := new(GetMediaStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mediaServiceClient) GetThumbnail(ctx context.Context, in *GetThumbnailRequest, opts ...grpc.CallOption) (*GetThumbnailResponse, error) {
	out := new(GetThumbnailResponse)
	err := c.cc.Invoke(ctx, MediaService_GetThumbnail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServiceServer is the server API for MediaService service.
// All implementations must embed UnimplementedMediaServiceServer
// for forward compatibility
type MediaServiceServer interface {
	UploadMedia(MediaService_UploadMediaServer) error
	GetMediaList(context.Context, *GetMediaListRequest) (*GetMediaListResponse, error)
	DeleteMedia(context.Context, *DeleteMediaRequest) (*DeleteMediaResponse, error)
	GetMediaMetadata(context.Context, *GetMediaMetadataRequest) (*GetMediaMetadataResponse, error)
	// Stream the original media binary (chunked). First message carries metadata.
	GetMediaStream(*GetMediaStreamRequest, MediaService_GetMediaStreamServer) error
	// Get a (cached) thumbnail for an image media, generated on demand.
	GetThumbnail(context.Context, *GetThumbnailRequest) (*GetThumbnailResponse, error)
	mustEmbedUnimplementedMediaServiceServer()
}

// UnimplementedMediaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMediaServiceServer struct {
}

func (UnimplementedMediaServiceServer) UploadMedia(MediaService_UploadMediaServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadMedia not implemented")
}
func (UnimplementedMediaServiceServer) GetMediaList(context.Context, *GetMediaListRequest) (*GetMediaListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaList not implemented")
}
func (UnimplementedMediaServiceServer) DeleteMedia(context.Context, *DeleteMediaRequest) (*DeleteMediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMedia not implemented")
}
func (UnimplementedMediaServiceServer) GetMediaMetadata(context.Context, *GetMediaMetadataRequest) (*GetMediaMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaMetadata not implemented")
}
func (UnimplementedMediaServiceServer) GetMediaStream(*GetMediaStreamRequest, MediaService_GetMediaStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMediaStream not implemented")
}
func (UnimplementedMediaServiceServer) GetThumbnail(context.Context, *GetThumbnailRequest) (*GetThumbnailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThumbnail not implemented")
}
func (UnimplementedMediaServiceServer) mustEmbedUnimplementedMediaServiceServer() {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_UploadMedia_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaServiceServer).UploadMedia(&mediaServiceUploadMediaServer{stream})
}

type MediaService_UploadMediaServer interface {
	SendAndClose(*UploadMediaResponse) error
	Recv() (*UploadMediaRequest, error)
	grpc.ServerStream
}

type mediaServiceUploadMediaServer struct {
	grpc.ServerStream
}

func (x *mediaServiceUploadMediaServer) SendAndClose(m *UploadMediaResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mediaServiceUploadMediaServer) Recv() (*UploadMediaRequest, error) {
	m := new(UploadMediaRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MediaService_GetMediaList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetMediaList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetMediaList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetMediaList(ctx, req.(*GetMediaListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_DeleteMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).DeleteMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_DeleteMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).DeleteMedia(ctx, req.(*DeleteMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetMediaMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetMediaMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetMediaMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetMediaMetadata(ctx, req.(*GetMediaMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetMediaStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMediaStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MediaServiceServer).GetMediaStream(m, &mediaServiceGetMediaStreamServer{stream})
}

type MediaService_GetMediaStreamServer interface {
	Send(*GetMediaStreamResponse) error
	grpc.ServerStream
}

type mediaServiceGetMediaStreamServer struct {
	grpc.ServerStream
}

func (x *mediaServiceGetMediaStreamServer) Send(m *GetMediaStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MediaService_GetThumbnail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThumbnailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetThumbnail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetThumbnail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetThumbnail(ctx, req.(*GetThumbnailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "media.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMediaList",
			Handler:    _MediaService_GetMediaList_Handler,
		},
		{
			MethodName: "DeleteMedia",
			Handler:    _MediaService_DeleteMedia_Handler,
		},
		{
			MethodName: "GetMediaMetadata",
			Handler:    _MediaService_GetMediaMetadata_Handler,
		},
		{
			MethodName: "GetThumbnail",
			Handler:    _MediaService_GetThumbnail_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadMedia",
			Handler:       _MediaService_UploadMedia_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetMediaStream",
			Handler:       _MediaService_GetMediaStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "media.proto",
}
