// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.DeleteMediaResponse in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Delete media response
 */
public class DeleteMediaResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val status: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val message: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "deletedCount",
    schemaIndex = 2,
  )
  public val deleted_count: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DeleteMediaResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DeleteMediaResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (status != other.status) return false
    if (message != other.message) return false
    if (deleted_count != other.deleted_count) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + status.hashCode()
      result = result * 37 + message.hashCode()
      result = result * 37 + deleted_count.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """status=${sanitize(status)}"""
    result += """message=${sanitize(message)}"""
    result += """deleted_count=$deleted_count"""
    return result.joinToString(prefix = "DeleteMediaResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    status: String = this.status,
    message: String = this.message,
    deleted_count: Int = this.deleted_count,
    unknownFields: ByteString = this.unknownFields,
  ): DeleteMediaResponse = DeleteMediaResponse(status, message, deleted_count, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DeleteMediaResponse> =
        object : ProtoAdapter<DeleteMediaResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      DeleteMediaResponse::class, 
      "type.googleapis.com/media.DeleteMediaResponse", 
      PROTO_3, 
      null, 
      "media.proto"
    ) {
      override fun encodedSize(`value`: DeleteMediaResponse): Int {
        var size = value.unknownFields.size
        if (value.status != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.status)
        }
        if (value.message != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.message)
        }
        if (value.deleted_count != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.deleted_count)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DeleteMediaResponse) {
        if (value.status != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.status)
        }
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.message)
        }
        if (value.deleted_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.deleted_count)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DeleteMediaResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.deleted_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.deleted_count)
        }
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.message)
        }
        if (value.status != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.status)
        }
      }

      override fun decode(reader: ProtoReader): DeleteMediaResponse {
        var status: String = ""
        var message: String = ""
        var deleted_count: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> status = ProtoAdapter.STRING.decode(reader)
            2 -> message = ProtoAdapter.STRING.decode(reader)
            3 -> deleted_count = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DeleteMediaResponse(
          status = status,
          message = message,
          deleted_count = deleted_count,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DeleteMediaResponse): DeleteMediaResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
