// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.GetMediaListRequest in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Get media list request
 */
public class GetMediaListRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val page: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "pageSize",
    schemaIndex = 1,
  )
  public val page_size: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "media.MediaType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "filterType",
    schemaIndex = 2,
  )
  public val filter_type: MediaType = MediaType.IMAGE,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "searchQuery",
    schemaIndex = 3,
  )
  public val search_query: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetMediaListRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetMediaListRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (page != other.page) return false
    if (page_size != other.page_size) return false
    if (filter_type != other.filter_type) return false
    if (search_query != other.search_query) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + page.hashCode()
      result = result * 37 + page_size.hashCode()
      result = result * 37 + filter_type.hashCode()
      result = result * 37 + search_query.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """page=$page"""
    result += """page_size=$page_size"""
    result += """filter_type=$filter_type"""
    result += """search_query=${sanitize(search_query)}"""
    return result.joinToString(prefix = "GetMediaListRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    page: Int = this.page,
    page_size: Int = this.page_size,
    filter_type: MediaType = this.filter_type,
    search_query: String = this.search_query,
    unknownFields: ByteString = this.unknownFields,
  ): GetMediaListRequest = GetMediaListRequest(page, page_size, filter_type, search_query, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetMediaListRequest> =
        object : ProtoAdapter<GetMediaListRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetMediaListRequest::class, 
      "type.googleapis.com/media.GetMediaListRequest", 
      PROTO_3, 
      null, 
      "media.proto"
    ) {
      override fun encodedSize(`value`: GetMediaListRequest): Int {
        var size = value.unknownFields.size
        if (value.page != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.page)
        }
        if (value.page_size != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.page_size)
        }
        if (value.filter_type != media.MediaType.IMAGE) {
          size += MediaType.ADAPTER.encodedSizeWithTag(3, value.filter_type)
        }
        if (value.search_query != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.search_query)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetMediaListRequest) {
        if (value.page != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.page)
        }
        if (value.page_size != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.page_size)
        }
        if (value.filter_type != media.MediaType.IMAGE) {
          MediaType.ADAPTER.encodeWithTag(writer, 3, value.filter_type)
        }
        if (value.search_query != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.search_query)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetMediaListRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.search_query != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.search_query)
        }
        if (value.filter_type != media.MediaType.IMAGE) {
          MediaType.ADAPTER.encodeWithTag(writer, 3, value.filter_type)
        }
        if (value.page_size != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.page_size)
        }
        if (value.page != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.page)
        }
      }

      override fun decode(reader: ProtoReader): GetMediaListRequest {
        var page: Int = 0
        var page_size: Int = 0
        var filter_type: MediaType = MediaType.IMAGE
        var search_query: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> page = ProtoAdapter.INT32.decode(reader)
            2 -> page_size = ProtoAdapter.INT32.decode(reader)
            3 -> try {
              filter_type = MediaType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            4 -> search_query = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetMediaListRequest(
          page = page,
          page_size = page_size,
          filter_type = filter_type,
          search_query = search_query,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetMediaListRequest): GetMediaListRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
