// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.GetMediaListResponse in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Get media list response
 */
public class GetMediaListResponse(
  media_list: List<MediaMetadata> = emptyList(),
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "totalCount",
    schemaIndex = 1,
  )
  public val total_count: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val page: Int = 0,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "pageSize",
    schemaIndex = 3,
  )
  public val page_size: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetMediaListResponse, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "media.MediaMetadata#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "mediaList",
    schemaIndex = 0,
  )
  public val media_list: List<MediaMetadata> = immutableCopyOf("media_list", media_list)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetMediaListResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (media_list != other.media_list) return false
    if (total_count != other.total_count) return false
    if (page != other.page) return false
    if (page_size != other.page_size) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + media_list.hashCode()
      result = result * 37 + total_count.hashCode()
      result = result * 37 + page.hashCode()
      result = result * 37 + page_size.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (media_list.isNotEmpty()) result += """media_list=$media_list"""
    result += """total_count=$total_count"""
    result += """page=$page"""
    result += """page_size=$page_size"""
    return result.joinToString(prefix = "GetMediaListResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    media_list: List<MediaMetadata> = this.media_list,
    total_count: Int = this.total_count,
    page: Int = this.page,
    page_size: Int = this.page_size,
    unknownFields: ByteString = this.unknownFields,
  ): GetMediaListResponse = GetMediaListResponse(media_list, total_count, page, page_size, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetMediaListResponse> =
        object : ProtoAdapter<GetMediaListResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetMediaListResponse::class, 
      "type.googleapis.com/media.GetMediaListResponse", 
      PROTO_3, 
      null, 
      "media.proto"
    ) {
      override fun encodedSize(`value`: GetMediaListResponse): Int {
        var size = value.unknownFields.size
        size += MediaMetadata.ADAPTER.asRepeated().encodedSizeWithTag(1, value.media_list)
        if (value.total_count != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.total_count)
        }
        if (value.page != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.page)
        }
        if (value.page_size != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.page_size)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetMediaListResponse) {
        MediaMetadata.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.media_list)
        if (value.total_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.total_count)
        }
        if (value.page != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.page)
        }
        if (value.page_size != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.page_size)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetMediaListResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.page_size != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.page_size)
        }
        if (value.page != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.page)
        }
        if (value.total_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.total_count)
        }
        MediaMetadata.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.media_list)
      }

      override fun decode(reader: ProtoReader): GetMediaListResponse {
        val media_list = mutableListOf<MediaMetadata>()
        var total_count: Int = 0
        var page: Int = 0
        var page_size: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> media_list.add(MediaMetadata.ADAPTER.decode(reader))
            2 -> total_count = ProtoAdapter.INT32.decode(reader)
            3 -> page = ProtoAdapter.INT32.decode(reader)
            4 -> page_size = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetMediaListResponse(
          media_list = media_list,
          total_count = total_count,
          page = page,
          page_size = page_size,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetMediaListResponse): GetMediaListResponse = value.copy(
        media_list = value.media_list.redactElements(MediaMetadata.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
