// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.GetMediaMetadataResponse in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Get media metadata response
 */
public class GetMediaMetadataResponse(
  @field:WireField(
    tag = 1,
    adapter = "media.MediaMetadata#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val metadata: MediaMetadata? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetMediaMetadataResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetMediaMetadataResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (metadata != other.metadata) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (metadata?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (metadata != null) result += """metadata=$metadata"""
    return result.joinToString(prefix = "GetMediaMetadataResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(metadata: MediaMetadata? = this.metadata, unknownFields: ByteString = this.unknownFields): GetMediaMetadataResponse = GetMediaMetadataResponse(metadata, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetMediaMetadataResponse> =
        object : ProtoAdapter<GetMediaMetadataResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetMediaMetadataResponse::class, 
      "type.googleapis.com/media.GetMediaMetadataResponse", 
      PROTO_3, 
      null, 
      "media.proto"
    ) {
      override fun encodedSize(`value`: GetMediaMetadataResponse): Int {
        var size = value.unknownFields.size
        if (value.metadata != null) {
          size += MediaMetadata.ADAPTER.encodedSizeWithTag(1, value.metadata)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetMediaMetadataResponse) {
        if (value.metadata != null) {
          MediaMetadata.ADAPTER.encodeWithTag(writer, 1, value.metadata)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetMediaMetadataResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.metadata != null) {
          MediaMetadata.ADAPTER.encodeWithTag(writer, 1, value.metadata)
        }
      }

      override fun decode(reader: ProtoReader): GetMediaMetadataResponse {
        var metadata: MediaMetadata? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> metadata = MediaMetadata.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetMediaMetadataResponse(
          metadata = metadata,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetMediaMetadataResponse): GetMediaMetadataResponse = value.copy(
        metadata = value.metadata?.let(MediaMetadata.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
