// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.GetMediaStreamRequest in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Get media stream (original binary) request
 */
public class GetMediaStreamRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "mediaId",
    schemaIndex = 0,
  )
  public val media_id: String = "",
  /**
   * byte offset to start reading from (0-based), optional, defaults to 0
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val offset: Long = 0L,
  /**
   * number of bytes to stream, 0 means until EOF
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val length: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetMediaStreamRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetMediaStreamRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (media_id != other.media_id) return false
    if (offset != other.offset) return false
    if (length != other.length) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + media_id.hashCode()
      result = result * 37 + offset.hashCode()
      result = result * 37 + length.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """media_id=${sanitize(media_id)}"""
    result += """offset=$offset"""
    result += """length=$length"""
    return result.joinToString(prefix = "GetMediaStreamRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    media_id: String = this.media_id,
    offset: Long = this.offset,
    length: Long = this.length,
    unknownFields: ByteString = this.unknownFields,
  ): GetMediaStreamRequest = GetMediaStreamRequest(media_id, offset, length, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetMediaStreamRequest> =
        object : ProtoAdapter<GetMediaStreamRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetMediaStreamRequest::class, 
      "type.googleapis.com/media.GetMediaStreamRequest", 
      PROTO_3, 
      null, 
      "media.proto"
    ) {
      override fun encodedSize(`value`: GetMediaStreamRequest): Int {
        var size = value.unknownFields.size
        if (value.media_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.media_id)
        }
        if (value.offset != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(2, value.offset)
        }
        if (value.length != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(3, value.length)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetMediaStreamRequest) {
        if (value.media_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.media_id)
        }
        if (value.offset != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.offset)
        }
        if (value.length != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 3, value.length)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetMediaStreamRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.length != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 3, value.length)
        }
        if (value.offset != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.offset)
        }
        if (value.media_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.media_id)
        }
      }

      override fun decode(reader: ProtoReader): GetMediaStreamRequest {
        var media_id: String = ""
        var offset: Long = 0L
        var length: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> media_id = ProtoAdapter.STRING.decode(reader)
            2 -> offset = ProtoAdapter.INT64.decode(reader)
            3 -> length = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetMediaStreamRequest(
          media_id = media_id,
          offset = offset,
          length = length,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetMediaStreamRequest): GetMediaStreamRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
