// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.GetMediaMetadataRequest in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Get media metadata request
 */
public class GetMediaMetadataRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "mediaId",
    schemaIndex = 0,
  )
  public val media_id: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetMediaMetadataRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetMediaMetadataRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (media_id != other.media_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + media_id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """media_id=${sanitize(media_id)}"""
    return result.joinToString(prefix = "GetMediaMetadataRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(media_id: String = this.media_id, unknownFields: ByteString = this.unknownFields): GetMediaMetadataRequest = GetMediaMetadataRequest(media_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetMediaMetadataRequest> =
        object : ProtoAdapter<GetMediaMetadataRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetMediaMetadataRequest::class, 
      "type.googleapis.com/media.GetMediaMetadataRequest", 
      PROTO_3, 
      null, 
      "media.proto"
    ) {
      override fun encodedSize(`value`: GetMediaMetadataRequest): Int {
        var size = value.unknownFields.size
        if (value.media_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.media_id)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetMediaMetadataRequest) {
        if (value.media_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.media_id)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetMediaMetadataRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.media_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.media_id)
        }
      }

      override fun decode(reader: ProtoReader): GetMediaMetadataRequest {
        var media_id: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> media_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetMediaMetadataRequest(
          media_id = media_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetMediaMetadataRequest): GetMediaMetadataRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
