// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.GetThumbnailRequest in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Get thumbnail request
 */
public class GetThumbnailRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "mediaId",
    schemaIndex = 0,
  )
  public val media_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "media.ThumbnailSize#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val size: ThumbnailSize = ThumbnailSize.THUMBNAIL_SMALL,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetThumbnailRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetThumbnailRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (media_id != other.media_id) return false
    if (size != other.size) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + media_id.hashCode()
      result = result * 37 + size.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """media_id=${sanitize(media_id)}"""
    result += """size=$size"""
    return result.joinToString(prefix = "GetThumbnailRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    media_id: String = this.media_id,
    size: ThumbnailSize = this.size,
    unknownFields: ByteString = this.unknownFields,
  ): GetThumbnailRequest = GetThumbnailRequest(media_id, size, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetThumbnailRequest> =
        object : ProtoAdapter<GetThumbnailRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetThumbnailRequest::class, 
      "type.googleapis.com/media.GetThumbnailRequest", 
      PROTO_3, 
      null, 
      "media.proto"
    ) {
      override fun encodedSize(`value`: GetThumbnailRequest): Int {
        var size_ = value.unknownFields.size
        if (value.media_id != "") {
          size_ += ProtoAdapter.STRING.encodedSizeWithTag(1, value.media_id)
        }
        if (value.size != media.ThumbnailSize.THUMBNAIL_SMALL) {
          size_ += ThumbnailSize.ADAPTER.encodedSizeWithTag(2, value.size)
        }
        return size_
      }

      override fun encode(writer: ProtoWriter, `value`: GetThumbnailRequest) {
        if (value.media_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.media_id)
        }
        if (value.size != media.ThumbnailSize.THUMBNAIL_SMALL) {
          ThumbnailSize.ADAPTER.encodeWithTag(writer, 2, value.size)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetThumbnailRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.size != media.ThumbnailSize.THUMBNAIL_SMALL) {
          ThumbnailSize.ADAPTER.encodeWithTag(writer, 2, value.size)
        }
        if (value.media_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.media_id)
        }
      }

      override fun decode(reader: ProtoReader): GetThumbnailRequest {
        var media_id: String = ""
        var size: ThumbnailSize = ThumbnailSize.THUMBNAIL_SMALL
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> media_id = ProtoAdapter.STRING.decode(reader)
            2 -> try {
              size = ThumbnailSize.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return GetThumbnailRequest(
          media_id = media_id,
          size = size,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetThumbnailRequest): GetThumbnailRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
