// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.GetThumbnailResponse in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Get thumbnail response
 */
public class GetThumbnailResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "data",
    schemaIndex = 0,
  )
  public val data_: ByteString = ByteString.EMPTY,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "mimeType",
    schemaIndex = 1,
  )
  public val mime_type: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val width: Int = 0,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val height: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetThumbnailResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetThumbnailResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (data_ != other.data_) return false
    if (mime_type != other.mime_type) return false
    if (width != other.width) return false
    if (height != other.height) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + data_.hashCode()
      result = result * 37 + mime_type.hashCode()
      result = result * 37 + width.hashCode()
      result = result * 37 + height.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """data_=$data_"""
    result += """mime_type=${sanitize(mime_type)}"""
    result += """width=$width"""
    result += """height=$height"""
    return result.joinToString(prefix = "GetThumbnailResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    data_: ByteString = this.data_,
    mime_type: String = this.mime_type,
    width: Int = this.width,
    height: Int = this.height,
    unknownFields: ByteString = this.unknownFields,
  ): GetThumbnailResponse = GetThumbnailResponse(data_, mime_type, width, height, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetThumbnailResponse> =
        object : ProtoAdapter<GetThumbnailResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetThumbnailResponse::class, 
      "type.googleapis.com/media.GetThumbnailResponse", 
      PROTO_3, 
      null, 
      "media.proto"
    ) {
      override fun encodedSize(`value`: GetThumbnailResponse): Int {
        var size = value.unknownFields.size
        if (value.data_ != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(1, value.data_)
        }
        if (value.mime_type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.mime_type)
        }
        if (value.width != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.width)
        }
        if (value.height != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.height)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetThumbnailResponse) {
        if (value.data_ != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.data_)
        }
        if (value.mime_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.mime_type)
        }
        if (value.width != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.width)
        }
        if (value.height != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.height)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetThumbnailResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.height != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.height)
        }
        if (value.width != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.width)
        }
        if (value.mime_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.mime_type)
        }
        if (value.data_ != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.data_)
        }
      }

      override fun decode(reader: ProtoReader): GetThumbnailResponse {
        var data_: ByteString = ByteString.EMPTY
        var mime_type: String = ""
        var width: Int = 0
        var height: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> data_ = ProtoAdapter.BYTES.decode(reader)
            2 -> mime_type = ProtoAdapter.STRING.decode(reader)
            3 -> width = ProtoAdapter.INT32.decode(reader)
            4 -> height = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetThumbnailResponse(
          data_ = data_,
          mime_type = mime_type,
          width = width,
          height = height,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetThumbnailResponse): GetThumbnailResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
