// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.MediaType in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Media types
 */
public enum class MediaType(
  override val `value`: Int,
) : WireEnum {
  IMAGE(0),
  LIVE_PHOTO(1),
  VIDEO(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MediaType> = object : EnumAdapter<MediaType>(
      MediaType::class, 
      PROTO_3, 
      MediaType.IMAGE
    ) {
      override fun fromValue(`value`: Int): MediaType? = MediaType.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): MediaType? = when (`value`) {
      0 -> IMAGE
      1 -> LIVE_PHOTO
      2 -> VIDEO
      else -> null
    }
  }
}
