// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.MediaMetadata in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

/**
 * Media metadata
 */
public class MediaMetadata(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val filename: String = "",
  @field:WireField(
    tag = 3,
    adapter = "media.MediaType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val type: MediaType = MediaType.IMAGE,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val size: Long = 0L,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "mimeType",
    schemaIndex = 4,
  )
  public val mime_type: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "createdAt",
    schemaIndex = 5,
  )
  public val created_at: Long = 0L,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "updatedAt",
    schemaIndex = 6,
  )
  public val updated_at: Long = 0L,
  exif_data: Map<String, String> = emptyMap(),
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "isLivePhoto",
    schemaIndex = 8,
  )
  public val is_live_photo: Boolean = false,
  /**
   * For Live Photos, reference to video file
   */
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "livePhotoVideoId",
    schemaIndex = 9,
  )
  public val live_photo_video_id: String = "",
  /**
   * Image width in pixels
   */
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 10,
  )
  public val width: Int = 0,
  /**
   * Image height in pixels
   */
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 11,
  )
  public val height: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<MediaMetadata, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 8,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "exifData",
    schemaIndex = 7,
  )
  public val exif_data: Map<String, String> = immutableCopyOf("exif_data", exif_data)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is MediaMetadata) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (filename != other.filename) return false
    if (type != other.type) return false
    if (size != other.size) return false
    if (mime_type != other.mime_type) return false
    if (created_at != other.created_at) return false
    if (updated_at != other.updated_at) return false
    if (exif_data != other.exif_data) return false
    if (is_live_photo != other.is_live_photo) return false
    if (live_photo_video_id != other.live_photo_video_id) return false
    if (width != other.width) return false
    if (height != other.height) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + filename.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + size.hashCode()
      result = result * 37 + mime_type.hashCode()
      result = result * 37 + created_at.hashCode()
      result = result * 37 + updated_at.hashCode()
      result = result * 37 + exif_data.hashCode()
      result = result * 37 + is_live_photo.hashCode()
      result = result * 37 + live_photo_video_id.hashCode()
      result = result * 37 + width.hashCode()
      result = result * 37 + height.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    result += """filename=${sanitize(filename)}"""
    result += """type=$type"""
    result += """size=$size"""
    result += """mime_type=${sanitize(mime_type)}"""
    result += """created_at=$created_at"""
    result += """updated_at=$updated_at"""
    if (exif_data.isNotEmpty()) result += """exif_data=$exif_data"""
    result += """is_live_photo=$is_live_photo"""
    result += """live_photo_video_id=${sanitize(live_photo_video_id)}"""
    result += """width=$width"""
    result += """height=$height"""
    return result.joinToString(prefix = "MediaMetadata{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: String = this.id,
    filename: String = this.filename,
    type: MediaType = this.type,
    size: Long = this.size,
    mime_type: String = this.mime_type,
    created_at: Long = this.created_at,
    updated_at: Long = this.updated_at,
    exif_data: Map<String, String> = this.exif_data,
    is_live_photo: Boolean = this.is_live_photo,
    live_photo_video_id: String = this.live_photo_video_id,
    width: Int = this.width,
    height: Int = this.height,
    unknownFields: ByteString = this.unknownFields,
  ): MediaMetadata = MediaMetadata(id, filename, type, size, mime_type, created_at, updated_at, exif_data, is_live_photo, live_photo_video_id, width, height, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MediaMetadata> = object : ProtoAdapter<MediaMetadata>(
      FieldEncoding.LENGTH_DELIMITED, 
      MediaMetadata::class, 
      "type.googleapis.com/media.MediaMetadata", 
      PROTO_3, 
      null, 
      "media.proto"
    ) {
      private val exif_dataAdapter: ProtoAdapter<Map<String, String>> by
          lazy { ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: MediaMetadata): Int {
        var size_ = value.unknownFields.size
        if (value.id != "") {
          size_ += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        }
        if (value.filename != "") {
          size_ += ProtoAdapter.STRING.encodedSizeWithTag(2, value.filename)
        }
        if (value.type != media.MediaType.IMAGE) {
          size_ += MediaType.ADAPTER.encodedSizeWithTag(3, value.type)
        }
        if (value.size != 0L) {
          size_ += ProtoAdapter.INT64.encodedSizeWithTag(4, value.size)
        }
        if (value.mime_type != "") {
          size_ += ProtoAdapter.STRING.encodedSizeWithTag(5, value.mime_type)
        }
        if (value.created_at != 0L) {
          size_ += ProtoAdapter.INT64.encodedSizeWithTag(6, value.created_at)
        }
        if (value.updated_at != 0L) {
          size_ += ProtoAdapter.INT64.encodedSizeWithTag(7, value.updated_at)
        }
        size_ += exif_dataAdapter.encodedSizeWithTag(8, value.exif_data)
        if (value.is_live_photo != false) {
          size_ += ProtoAdapter.BOOL.encodedSizeWithTag(9, value.is_live_photo)
        }
        if (value.live_photo_video_id != "") {
          size_ += ProtoAdapter.STRING.encodedSizeWithTag(10, value.live_photo_video_id)
        }
        if (value.width != 0) {
          size_ += ProtoAdapter.INT32.encodedSizeWithTag(11, value.width)
        }
        if (value.height != 0) {
          size_ += ProtoAdapter.INT32.encodedSizeWithTag(12, value.height)
        }
        return size_
      }

      override fun encode(writer: ProtoWriter, `value`: MediaMetadata) {
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
        if (value.filename != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.filename)
        }
        if (value.type != media.MediaType.IMAGE) {
          MediaType.ADAPTER.encodeWithTag(writer, 3, value.type)
        }
        if (value.size != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 4, value.size)
        }
        if (value.mime_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.mime_type)
        }
        if (value.created_at != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 6, value.created_at)
        }
        if (value.updated_at != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 7, value.updated_at)
        }
        exif_dataAdapter.encodeWithTag(writer, 8, value.exif_data)
        if (value.is_live_photo != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 9, value.is_live_photo)
        }
        if (value.live_photo_video_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 10, value.live_photo_video_id)
        }
        if (value.width != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 11, value.width)
        }
        if (value.height != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 12, value.height)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: MediaMetadata) {
        writer.writeBytes(value.unknownFields)
        if (value.height != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 12, value.height)
        }
        if (value.width != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 11, value.width)
        }
        if (value.live_photo_video_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 10, value.live_photo_video_id)
        }
        if (value.is_live_photo != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 9, value.is_live_photo)
        }
        exif_dataAdapter.encodeWithTag(writer, 8, value.exif_data)
        if (value.updated_at != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 7, value.updated_at)
        }
        if (value.created_at != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 6, value.created_at)
        }
        if (value.mime_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.mime_type)
        }
        if (value.size != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 4, value.size)
        }
        if (value.type != media.MediaType.IMAGE) {
          MediaType.ADAPTER.encodeWithTag(writer, 3, value.type)
        }
        if (value.filename != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.filename)
        }
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): MediaMetadata {
        var id: String = ""
        var filename: String = ""
        var type: MediaType = MediaType.IMAGE
        var size: Long = 0L
        var mime_type: String = ""
        var created_at: Long = 0L
        var updated_at: Long = 0L
        val exif_data = mutableMapOf<String, String>()
        var is_live_photo: Boolean = false
        var live_photo_video_id: String = ""
        var width: Int = 0
        var height: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> filename = ProtoAdapter.STRING.decode(reader)
            3 -> try {
              type = MediaType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            4 -> size = ProtoAdapter.INT64.decode(reader)
            5 -> mime_type = ProtoAdapter.STRING.decode(reader)
            6 -> created_at = ProtoAdapter.INT64.decode(reader)
            7 -> updated_at = ProtoAdapter.INT64.decode(reader)
            8 -> exif_data.putAll(exif_dataAdapter.decode(reader))
            9 -> is_live_photo = ProtoAdapter.BOOL.decode(reader)
            10 -> live_photo_video_id = ProtoAdapter.STRING.decode(reader)
            11 -> width = ProtoAdapter.INT32.decode(reader)
            12 -> height = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return MediaMetadata(
          id = id,
          filename = filename,
          type = type,
          size = size,
          mime_type = mime_type,
          created_at = created_at,
          updated_at = updated_at,
          exif_data = exif_data,
          is_live_photo = is_live_photo,
          live_photo_video_id = live_photo_video_id,
          width = width,
          height = height,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: MediaMetadata): MediaMetadata = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
