// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.ThumbnailSize in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Thumbnail size preset
 */
public enum class ThumbnailSize(
  override val `value`: Int,
) : WireEnum {
  /**
   * ~128px on the long edge
   */
  THUMBNAIL_SMALL(0),
  /**
   * ~256px
   */
  THUMBNAIL_MEDIUM(1),
  /**
   * ~512px
   */
  THUMBNAIL_LARGE(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ThumbnailSize> = object : EnumAdapter<ThumbnailSize>(
      ThumbnailSize::class, 
      PROTO_3, 
      ThumbnailSize.THUMBNAIL_SMALL
    ) {
      override fun fromValue(`value`: Int): ThumbnailSize? = ThumbnailSize.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ThumbnailSize? = when (`value`) {
      0 -> THUMBNAIL_SMALL
      1 -> THUMBNAIL_MEDIUM
      2 -> THUMBNAIL_LARGE
      else -> null
    }
  }
}
