// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.UploadMediaRequest in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Upload request - streamed for large files
 */
public class UploadMediaRequest(
  @field:WireField(
    tag = 1,
    adapter = "media.MediaMetadata#ADAPTER",
    oneofName = "data",
    schemaIndex = 0,
  )
  public val metadata: MediaMetadata? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    jsonName = "chunkData",
    oneofName = "data",
    schemaIndex = 1,
  )
  public val chunk_data: ByteString? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<UploadMediaRequest, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(metadata, chunk_data) <= 1) {
      "At most one of metadata, chunk_data may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UploadMediaRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (metadata != other.metadata) return false
    if (chunk_data != other.chunk_data) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (metadata?.hashCode() ?: 0)
      result = result * 37 + (chunk_data?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (metadata != null) result += """metadata=$metadata"""
    if (chunk_data != null) result += """chunk_data=$chunk_data"""
    return result.joinToString(prefix = "UploadMediaRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    metadata: MediaMetadata? = this.metadata,
    chunk_data: ByteString? = this.chunk_data,
    unknownFields: ByteString = this.unknownFields,
  ): UploadMediaRequest = UploadMediaRequest(metadata, chunk_data, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<UploadMediaRequest> =
        object : ProtoAdapter<UploadMediaRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      UploadMediaRequest::class, 
      "type.googleapis.com/media.UploadMediaRequest", 
      PROTO_3, 
      null, 
      "media.proto"
    ) {
      override fun encodedSize(`value`: UploadMediaRequest): Int {
        var size = value.unknownFields.size
        size += MediaMetadata.ADAPTER.encodedSizeWithTag(1, value.metadata)
        size += ProtoAdapter.BYTES.encodedSizeWithTag(2, value.chunk_data)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: UploadMediaRequest) {
        MediaMetadata.ADAPTER.encodeWithTag(writer, 1, value.metadata)
        ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.chunk_data)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: UploadMediaRequest) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.chunk_data)
        MediaMetadata.ADAPTER.encodeWithTag(writer, 1, value.metadata)
      }

      override fun decode(reader: ProtoReader): UploadMediaRequest {
        var metadata: MediaMetadata? = null
        var chunk_data: ByteString? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> metadata = MediaMetadata.ADAPTER.decode(reader)
            2 -> chunk_data = ProtoAdapter.BYTES.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UploadMediaRequest(
          metadata = metadata,
          chunk_data = chunk_data,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: UploadMediaRequest): UploadMediaRequest = value.copy(
        metadata = value.metadata?.let(MediaMetadata.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
