// Code generated by Wire protocol buffer compiler, do not edit.
// Source: media.UploadMediaResponse in media.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package media

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Upload response
 */
public class UploadMediaResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "mediaId",
    schemaIndex = 0,
  )
  public val media_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val status: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val message: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<UploadMediaResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UploadMediaResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (media_id != other.media_id) return false
    if (status != other.status) return false
    if (message != other.message) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + media_id.hashCode()
      result = result * 37 + status.hashCode()
      result = result * 37 + message.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """media_id=${sanitize(media_id)}"""
    result += """status=${sanitize(status)}"""
    result += """message=${sanitize(message)}"""
    return result.joinToString(prefix = "UploadMediaResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    media_id: String = this.media_id,
    status: String = this.status,
    message: String = this.message,
    unknownFields: ByteString = this.unknownFields,
  ): UploadMediaResponse = UploadMediaResponse(media_id, status, message, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<UploadMediaResponse> =
        object : ProtoAdapter<UploadMediaResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      UploadMediaResponse::class, 
      "type.googleapis.com/media.UploadMediaResponse", 
      PROTO_3, 
      null, 
      "media.proto"
    ) {
      override fun encodedSize(`value`: UploadMediaResponse): Int {
        var size = value.unknownFields.size
        if (value.media_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.media_id)
        }
        if (value.status != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.status)
        }
        if (value.message != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.message)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: UploadMediaResponse) {
        if (value.media_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.media_id)
        }
        if (value.status != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.status)
        }
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.message)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: UploadMediaResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.message)
        }
        if (value.status != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.status)
        }
        if (value.media_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.media_id)
        }
      }

      override fun decode(reader: ProtoReader): UploadMediaResponse {
        var media_id: String = ""
        var status: String = ""
        var message: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> media_id = ProtoAdapter.STRING.decode(reader)
            2 -> status = ProtoAdapter.STRING.decode(reader)
            3 -> message = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UploadMediaResponse(
          media_id = media_id,
          status = status,
          message = message,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: UploadMediaResponse): UploadMediaResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
